on:
  push:
  workflow_dispatch:         
jobs:
  event-handler:
    runs-on: windows-latest  
    env:
        token: ${{ secrets.SECRET_TOKEN }}
    steps:  
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Getting Github Credentials
        run: |
          git config --global user.email "carldomond7@gmail.com"
          git config --global user.name "carldomond7"
      - name: Run Powershell Script
        run: |
          pwsh -File poke.ps1
          git config --global user.email "carldomond7@gmail.com"
          git config --global user.name "carldomond7"
          git commit -m "New Infernape has Appeared"
          git push origin main
        shell: pwsh
          
